# Generated by Django 2.2.2 on 2019-06-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntitle', models.CharField(max_length=60)),
                ('ncontent', models.TextField()),
                ('npub_date', models.DateTimeField(auto_now_add=True)),
                ('typeinfo', models.ManyToManyField(to='books.TypeInfo')),
            ],
        ),
    ]
